import { createGlobalTheme } from "@vanilla-extract/css";


export const typography = createGlobalTheme(":root", {
  // heading: {
  //   fontFamily: "Public Sans",
  //   fontStyle: "normal",
  //   fontWeight: 600,
  //   fontSize: {
  //     xs: "15px",
  //     s: "18px",
  //     m: "21px",
  //     l: "24px",
  //     xl: "27px",
  //   },
  //   lineHeight: {
  //     xs: "18px",
  //     s: "21px",
  //     m: "24px",
  //     l: "27px",
  //     xl: "30px",
  //   },
  // },
  // title: {
  //   fontFamily: "Public Sans",
  //   fontStyle: "normal",
  //   fontWeight: 600,
  //   fontSize: {
  //     xs: "12px",
  //     s: "15px",
  //     m: "18px",
  //     l: "21px",
  //     xl: "24px",
  //   },
  //   lineHeight: {
  //     xs: "15px",
  //     s: "18px",
  //     m: "21px",
  //     l: "24px",
  //     xl: "27px",
  //   },
  // },
  // body: {
  //   fontFamily: "Public Sans",
  //   fontStyle: "normal",
  //   fontWeight: 400,
  //   fontSize: {
  //     xs: "12px",
  //     s: "15px",
  //     m: "18px",
  //     l: "21px",
  //     xl: "24px",
  //   },
  //   lineHeight: {
  //     xs: "21px",
  //     s: "24px",
  //     m: "27px",
  //     l: "30px",
  //     xl: "33px",
  //   },
  // },
  action: {
    fontFamily: "Public Sans",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: {
      xs: "12px",
      sm: "15px",
      md: "18px",
      lg: "21px",
      xl: "24px",
    },
    lineHeight: {
      xs: "15px",
      sm: "18px",
      md: "21px",
      lg: "24px",
      xl: "27px",
    },
  },
  // label: {
  //   fontFamily: "Noto Sans Mono",
  //   fontStyle: "normal",
  //   fontWeight: 400,
  //   textTransform: "uppercase",
  //   fontSize: {
  //     xs: "9px",
  //     s: "12px",
  //     m: "15px",
  //     l: "18px",
  //     xl: "21px",
  //   },
  //   lineHeight: {
  //     xs: "12px",
  //     s: "15px",
  //     m: "18px",
  //     l: "21px",
  //     xl: "24px",
  //   },
  //   letterSpacing: {
  //     xs: "1.08px",
  //     s: "1.35px",
  //     m: "1.62px",
  //     l: "1.89px",
  //     xl: "2.16px",
  //   },
  // },
  // number: {
  //   fontFamily: "Noto Sans Mono",
  //   fontStyle: "normal",
  //   fontWeight: 400,
  //   fontSize: {
  //     xs: "18px",
  //     s: "21px",
  //     m: "24px",
  //     l: "27px",
  //     xl: "30px",
  //   },
  //   lineHeight: {
  //     xs: "21px",
  //     s: "24px",
  //     m: "27px",
  //     l: "30px",
  //     xl: "33px",
  //   },
  // },
});
