import { createGlobalTheme } from "@vanilla-extract/css";

export const typography = createGlobalTheme(":root", {
  heading: {
    fontFamily: "Public Sans",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: {
      xs: "15px",
      sm: "18px",
      md: "21px",
      lg: "24px",
      xl: "27px",
    },
    lineHeight: {
      xs: "18px",
      sm: "21px",
      md: "24px",
      lg: "27px",
      xl: "30px",
    },
  },
  title: {
    fontFamily: "Public Sans",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: {
      xs: "12px",
      sm: "15px",
      md: "18px",
      lg: "21px",
      xl: "24px",
    },
    lineHeight: {
      xs: "15px",
      sm: "18px",
      md: "21px",
      lg: "24px",
      xl: "27px",
    },
  },
  body: {
    fontFamily: "Public Sans",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: {
      xs: "12px",
      sm: "15px",
      md: "18px",
      lg: "21px",
      xl: "24px",
    },
    lineHeight: {
      xs: "21px",
      sm: "24px",
      md: "27px",
      lg: "30px",
      xl: "33px",
    },
  },
  action: {
    fontFamily: "Public Sans",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: {
      xs: "12px",
      sm: "15px",
      md: "18px",
      lg: "21px",
      xl: "24px",
    },
    lineHeight: {
      xs: "15px",
      sm: "18px",
      md: "21px",
      lg: "24px",
      xl: "27px",
    },
  },
  label: {
    fontFamily: "Noto Sans Mono",
    fontStyle: "normal",
    fontWeight: "400",
    textTransform: "uppercase",
    fontSize: {
      xs: "9px",
      sm: "12px",
      mf: "15px",
      lg: "18px",
      xl: "21px",
    },
    lineHeight: {
      xs: "12px",
      sm: "15px",
      md: "18px",
      lg: "21px",
      xl: "24px",
    },
    letterSpacing: {
      xs: "1.08px",
      sm: "1.35px",
      md: "1.62px",
      lg: "1.89px",
      xl: "2.16px",
    },
  },
  number: {
    fontFamily: "Noto Sans Mono",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: {
      xs: "18px",
      sm: "21px",
      md: "24px",
      lg: "27px",
      xl: "30px",
    },
    lineHeight: {
      xs: "21px",
      sm: "24px",
      md: "27px",
      lg: "30px",
      xl: "33px",
    },
  },
});
